### ISSUE TITLE
App crash when type any emoji

### ISSUE THREAD

**Issue by mip001hk** [tsekityam/Cangjie-Helper-for-Android#1]
1. Randomly type any non-emoji, won't crash
2. Switch to emoji keyboard and choose any of the emojis
3. Happy crashing

android.database.sqlite.SQLiteException: unrecognized token: "'🐧)" (code 1): , while compiling: SELECT codes.code FROM codes WHERE codes.version = 3 AND codes.char_index = (SELECT chars.char_index FROM chars WHERE chars.chchar = '��')

**Comment by tsekityam** [comment]
This is because SQLite doesn't recognize half emoji, then it throws an error. Now the error will be caught and the app will not crash because of this exception. There should be a better way to handle that, such as filtering out all the emoji before looking for the input code. I will work on it later.

Anyway, thanks for your report.
